In [4]:
# ndarray dtypes
import numpy as np
data = np.array([(1,2,3),(4,5,6)], dtype = np.float)
data

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
data.astype(np.complex)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [6]:
data

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
data_2 = np.array([(1,2,3),(4,5,6)], dtype = np.complex)
data + data_2

array([[ 2.+0.j,  4.+0.j,  6.+0.j],
       [ 8.+0.j, 10.+0.j, 12.+0.j]])

In [8]:
np.sqrt(data)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [9]:
# ndarray real and imag
data_2.real

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
data_2.imag

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.sqrt(data).real

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [12]:
np.sqrt(data).imag

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# ndarray with constant values
data_3 = np.empty(4)
data_3

array([0., 0., 0., 0.])

In [14]:
data_3.fill(6)

In [15]:
data_3

array([6., 6., 6., 6.])

In [16]:
data_4 = np.full(4,6)
data_4

array([6, 6, 6, 6])

In [17]:
#ndarray functions
data_5 = np.linspace(1,20,10)
data_5

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [18]:
data_6 = np.logspace(1,3,6)
data_6

array([  10.        ,   25.11886432,   63.09573445,  158.48931925,
        398.10717055, 1000.        ])

In [19]:
data_x = np.array([1,2,-3])
data_y = np.array((-2,1,3))
X,Y = np.meshgrid(data_x,data_y)
X

array([[ 1,  2, -3],
       [ 1,  2, -3],
       [ 1,  2, -3]])

In [20]:
Z = (X + Y) **2

In [21]:
Z

array([[ 1,  0, 25],
       [ 4,  9,  4],
       [16, 25,  0]], dtype=int32)

In [22]:
# Creating Uninitialized array
data_empty = np.empty(6,dtype = np.float)
data_empty

array([  10.        ,   25.11886432,   63.09573445,  158.48931925,
        398.10717055, 1000.        ])

In [23]:
# Arrays with same properties
def f(x):
    y = np.ones_like(x)
    z = np.zeros_like(x)
    w = np.empty_like(x)
    return w,y,z
f([4,1,7])

(array([-1754622928,         537,           0]),
 array([1, 1, 1]),
 array([0, 0, 0]))

In [24]:
# matrix arrays
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.diag(np.arange(0,10,1.5))

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1.5, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 3. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 4.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 6. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 7.5, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 9. ]])

In [27]:
# multidimwntional arrays
f = lambda m, n: n + 10 * m
A = np.fromfunction(f,(7,7),dtype = int)
A

array([[ 0,  1,  2,  3,  4,  5,  6],
       [10, 11, 12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24, 25, 26],
       [30, 31, 32, 33, 34, 35, 36],
       [40, 41, 42, 43, 44, 45, 46],
       [50, 51, 52, 53, 54, 55, 56],
       [60, 61, 62, 63, 64, 65, 66]])

In [28]:
B = A[1:5,1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [29]:
B[:,:] = 0
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
A

array([[ 0,  1,  2,  3,  4,  5,  6],
       [10,  0,  0,  0,  0, 15, 16],
       [20,  0,  0,  0,  0, 25, 26],
       [30,  0,  0,  0,  0, 35, 36],
       [40,  0,  0,  0,  0, 45, 46],
       [50, 51, 52, 53, 54, 55, 56],
       [60, 61, 62, 63, 64, 65, 66]])

In [31]:
C = A.copy()
C

array([[ 0,  1,  2,  3,  4,  5,  6],
       [10,  0,  0,  0,  0, 15, 16],
       [20,  0,  0,  0,  0, 25, 26],
       [30,  0,  0,  0,  0, 35, 36],
       [40,  0,  0,  0,  0, 45, 46],
       [50, 51, 52, 53, 54, 55, 56],
       [60, 61, 62, 63, 64, 65, 66]])

In [32]:
C is A

False

In [33]:
B.base is A

True

In [34]:
# Fancy Indexing and Boolean-Valued Indexing
i = np.linspace(0,2,12)
i

array([0.        , 0.18181818, 0.36363636, 0.54545455, 0.72727273,
       0.90909091, 1.09090909, 1.27272727, 1.45454545, 1.63636364,
       1.81818182, 2.        ])

In [35]:
i[np.array([2,4,7])]

array([0.36363636, 0.72727273, 1.27272727])

In [36]:
i[i > 1]

array([1.09090909, 1.27272727, 1.45454545, 1.63636364, 1.81818182,
       2.        ])

In [37]:
j = np.arange(15)
indices = [1,3,6]
k = i[j[indices]]
k

array([0.18181818, 0.54545455, 1.09090909])

In [38]:
k[1] = 2
k

array([0.18181818, 2.        , 1.09090909])

In [39]:
i

array([0.        , 0.18181818, 0.36363636, 0.54545455, 0.72727273,
       0.90909091, 1.09090909, 1.27272727, 1.45454545, 1.63636364,
       1.81818182, 2.        ])

In [40]:
# reshaping & resizing
p = np.arange(15).reshape(3,5)
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
p.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
p.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
p.squeeze()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
p.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [45]:
q = np.arange(5)
np.vstack([p,q])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [46]:
np.hstack((p,p))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

In [47]:
np.concatenate([p,p],axis =1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

In [48]:
np.add(p,q)

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [49]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
q

array([0, 1, 2, 3, 4])

In [51]:
np.subtract(q,p)

array([[  0,   0,   0,   0,   0],
       [ -5,  -5,  -5,  -5,  -5],
       [-10, -10, -10, -10, -10]])

In [52]:
# vectorize
def mult_div(x,y):
    return x / y if x > y else  x * y
mult_div(3,6)

18

In [53]:
mult_div_vectorize = np.vectorize(mult_div)
mult_div_vectorize([1,6,3],[8,2,6])

array([ 8,  3, 18])

In [54]:
np.argmax(q)

4

In [55]:
np.argmin(q)

0

In [56]:
q[4]

4

In [57]:
m = np.random.normal(size = (5,10,15))
m

array([[[-3.26995928e-02, -1.17079207e+00, -1.38435726e+00,
          1.03054723e+00,  4.65242570e-01,  2.99302609e-01,
          4.37634868e-01,  4.20008679e-02, -1.62010021e-01,
         -2.65003158e-01, -8.76414674e-01, -1.01822572e+00,
          1.27041553e-01,  5.88879910e-01,  9.52371204e-01],
        [ 4.62447509e-01, -4.23058691e-01,  5.27516705e-02,
          6.56743189e-01, -1.21422534e+00, -3.03528921e-01,
          1.17829501e+00, -2.35351637e+00,  2.35305927e-01,
         -4.26538976e-01, -1.45501475e-01, -3.37257191e-03,
          1.01309747e+00,  3.56433125e-01, -2.12717521e-01],
        [-2.91227780e-01,  3.96999767e-01, -1.13948133e+00,
          3.26124503e-01,  9.36610242e-02,  4.21023412e-01,
         -1.03757214e+00,  1.33713126e+00,  8.74664234e-01,
         -2.42618986e-01,  1.60888586e-01, -1.31090571e+00,
          1.05243677e+00, -3.21075632e-01,  9.45074568e-01],
        [-6.53286602e-01,  6.99890825e-02,  1.00525153e+00,
          2.48395205e+00,  1.26924981

In [58]:
m.sum(axis = 1)

array([[-1.70068695,  0.58943578, -1.69430883,  6.93814003,  0.76051213,
        -0.57388881, -0.4722184 ,  2.29478027,  0.86961634,  1.39364747,
        -2.01322513, -4.28726003,  5.45740784,  1.47127858,  4.349964  ],
       [ 2.13754302,  0.65499387,  3.18967345,  5.98308309, -1.49457004,
        -4.97506596,  3.10927058, -3.47001961, -0.73080243,  5.63871343,
         1.45940977,  0.28732713,  0.25316206,  1.65040965,  2.19974559],
       [ 2.21767476, -1.21773325,  0.24495891, -1.62635352,  2.51556181,
        -0.68796256, -4.3173173 , -1.4713746 , -2.06701765,  6.03232258,
        -1.38270735, -1.30317462,  5.25381223, -3.55605365, -2.10655246],
       [ 7.31947286, -3.92387661,  0.6767457 ,  1.87973796, -3.42020768,
        -2.32429264, -1.72609969,  1.53401101, -0.50296532,  2.0442127 ,
        -3.57130436, -2.87996231, -1.05777735,  0.17695935, -1.83553036],
       [ 0.90959725, -3.89031466, -1.28299666,  4.8033006 , -1.55229703,
        -4.59064113,  1.21554585,  0.9317767 , 

In [59]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
q

array([0, 1, 2, 3, 4])

In [61]:
# Boolean Arrays and Conditional Expressions
np.all(p < q)

False

In [63]:
np.any(p > q)

True

In [64]:
p > 2

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [68]:
2 * (p > 3)

array([[0, 0, 0, 0, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [75]:
np.select([p >4,p **2,p < -1],[p /2,p ** 3,p < 2])

D:\ML\anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: select condlists containing integer ndarrays is deprecated and will be removed in the future. Use `.astype(bool)` to convert to bools.
  """Entry point for launching an IPython kernel.


array([[ 0. ,  1. ,  8. , 27. , 64. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ]])

In [73]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
np.random.randn(1, 2, 3, 4, 5)

array([[[[[ 1.17793153, -0.78139998, -1.36146266,  1.5885137 ,
           -0.35676329],
          [-0.97066576, -0.76782208, -1.50459339, -0.43490542,
           -1.13085524],
          [ 0.44795242, -0.27585845,  0.23163544,  0.09503328,
            0.28926882],
          [ 1.3369584 ,  0.73308658,  0.18583429, -0.69736713,
            0.27405195]],

         [[ 1.31626912,  0.08397539, -0.54456228,  0.11636406,
           -0.90357583],
          [ 0.77765797,  0.75143349, -1.48312265,  0.15347233,
            1.69891821],
          [ 0.07796344,  0.18865001,  0.56245193, -0.75853319,
           -1.09001858],
          [ 0.35680564,  0.66629315, -0.03723721, -1.28587308,
           -0.67495779]],

         [[-1.98877006,  1.47753055,  0.53922446,  0.13164027,
            0.89995158],
          [-0.17457065,  1.16980677,  0.43696608, -0.7603645 ,
            0.62720204],
          [-0.40495998, -0.08462004, -0.99713341,  1.59301695,
           -0.79474858],
          [-0.11849829,  0.5

In [77]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([0, 1, 2, 3, 4])

In [79]:
# NumPy Functions for Operating on Sets
r = np.array(([4,8,1,-1,11],[14,-3,9,0,10],[20,24,15,30,-4]))
r

array([[ 4,  8,  1, -1, 11],
       [14, -3,  9,  0, 10],
       [20, 24, 15, 30, -4]])

In [82]:
np.in1d(p,r)

array([ True,  True, False, False,  True, False, False, False,  True,
        True,  True,  True, False, False,  True])

In [83]:
np.intersect1d(p,r)

array([ 0,  1,  4,  8,  9, 10, 11, 14])

In [85]:
np.setdiff1d(r,p)

array([-4, -3, -1, 15, 20, 24, 30])

In [86]:
np.union1d(p,r)

array([-4, -3, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 20, 24, 30])

In [88]:
# Summary of NumPy Functions for Matrix Operations
np.dot(p,q)

array([ 30,  80, 130])

In [89]:
p


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
q

array([0, 1, 2, 3, 4])

In [91]:
np.inner(p,r)

array([[ 51,  55, 128],
       [166, 205, 553],
       [281, 355, 978]])

In [94]:
np.outer(p,q)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16],
       [ 0,  5, 10, 15, 20],
       [ 0,  6, 12, 18, 24],
       [ 0,  7, 14, 21, 28],
       [ 0,  8, 16, 24, 32],
       [ 0,  9, 18, 27, 36],
       [ 0, 10, 20, 30, 40],
       [ 0, 11, 22, 33, 44],
       [ 0, 12, 24, 36, 48],
       [ 0, 13, 26, 39, 52],
       [ 0, 14, 28, 42, 56]])

In [97]:
np.kron(p,q)

array([[ 0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  0,  2,  4,  6,  8,  0,
         3,  6,  9, 12,  0,  4,  8, 12, 16],
       [ 0,  5, 10, 15, 20,  0,  6, 12, 18, 24,  0,  7, 14, 21, 28,  0,
         8, 16, 24, 32,  0,  9, 18, 27, 36],
       [ 0, 10, 20, 30, 40,  0, 11, 22, 33, 44,  0, 12, 24, 36, 48,  0,
        13, 26, 39, 52,  0, 14, 28, 42, 56]])